In [12]:
import cv2
import matplotlib
import matplotlib.pyplot as plt
from roipoly import RoiPoly
import numpy as np
import os
matplotlib.use('TkAgg') 
import pickle

In [13]:
def masking(image):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)  # Convert BGR to RGB for display
    
    plt.imshow(image)
    plt.title("Select ROI")
    plt.show()
    
    roi = RoiPoly(color='k')  # Draw ROI on the image


    roi.display_roi()
    plt.imshow(image)
    plt.title("Selected ROI")
    plt.show()

    mask = roi.get_mask(np.zeros((image.shape[0], image.shape[1])))

    
    return mask

def rgb_values(image, mask):
    masked_image = cv2.bitwise_and(image, image, mask=mask.astype(np.uint8))
    rgb_values = masked_image[mask > 0]#255 to match the filled mask value value will be either 0 or 255
    return rgb_values


In [14]:
# obtaining mask of all classes 
image_folder = 'data'

RGB_values_all_classes = []

for class_index in range(0, 4):
    
    RGB_values_img = []
    
    for i in range(1, 8):  # Loop from index 1 to 7
        filename= f'{i}.jpg'  
    
        image_path = os.path.join(image_folder, filename)  # constructing file path
        image=cv2.imread(image_path)
    
        mask = masking(image)
        


        rgb_values_img=rgb_values(image,mask)
    
    
        RGB_values_img.extend(rgb_values_img.tolist())
    

    
    
    RGB_values_array =np.array(RGB_values_img)

    mean= np.mean(RGB_values_array, axis=0)
    covariance=np.cov(RGB_values_array,rowvar=False)
    
    RGB_values_all_classes.append({
        'class': class_index,
        'mean': mean,
        'covariance': covariance
    })
    
    print(f"Class {class_index}: Mean = {mean}, Covariance = {covariance}")

# Load image


with open('RGB_values_all_classes_2.pkl', 'wb') as file:
    pickle.dump(RGB_values_all_classes, file)


# mask = masking(image)

# blue_val = rgb_values(image,mask)

# # Apply the mask to the original image
# segmented_image = cv2.bitwise_and(image, image, mask=mask.astype(np.uint8))

# # # Display the segmented image
# plt.imshow(segmented_image)
# plt.title("Segmented Image")
# plt.show()

Class 0: Mean = [106.63672708  94.17643923  32.87277896], Covariance = [[1560.86038001 1352.87485207  588.0772806 ]
 [1352.87485207 1306.65904857  909.4419068 ]
 [ 588.0772806   909.4419068  1629.0898107 ]]
Class 1: Mean = [ 73.25169909 188.15438247 204.9961917 ], Covariance = [[ 790.10785145  720.97449891  389.93568644]
 [ 720.97449891 1429.83185107 1296.97410411]
 [ 389.93568644 1296.97410411 1386.63143801]]
Class 2: Mean = [172.01582116 102.57507046  18.72918268], Covariance = [[3138.57530537 1908.27147253    6.09665568]
 [1908.27147253 1263.5897135   268.53291896]
 [   6.09665568  268.53291896  772.00031929]]
Class 3: Mean = [ 56.05070757  40.34222307 183.50626949], Covariance = [[ 508.61068507  675.36501924  776.15218993]
 [ 675.36501924  971.0770165  1002.83959673]
 [ 776.15218993 1002.83959673 1896.04938041]]
